### ISSUE TITLE
Option to turn off zero padding

### ISSUE THREAD

**Issue by adampbeardsley** [nithyanandan/MOFF#1]
It would be nice to turn off the zero padding in the MOFF imaging to speed things up when running small tests. For example, I'm working on calibration and it's nice to have the output images, but I don't need the precision of a padded image.

**Comment by nithyanandan** [comment]
The feature was requested on commit https://github.com/nithyanandan/MOFF/commit/631e2ca51dd6432354182771255fba827b8e07f0 on FX-accumulate branch.

In commit https://github.com/nithyanandan/MOFF/commit/6e802d8791486926a504db8af826678a7043dcad on FX-accumulate branch, I have added an input keyword pad in imagr() member function of class NewImage. It can be set to 'on' (default) or 'off'. If set to 'on' the padded uv-grid is 4 times the antenna array grid in either direction in case of MOFF and twice the interferometer array grid in either direction in case of FX. 

Currently the padding is a binary toggle between 'on' and 'off' and the padding size is determined automatically as specified above and not user specified but can be a feature for the future.

Preliminary testing is successful. Waiting for more testing and feedback...

**Comment by adampbeardsley** [comment]
Works from my end, thanks!

**Comment by nithyanandan** [comment]
Reopening to switch from a binary choice of whether to have this pre-set padding on or off to have it flexible and controllable by the user.

**Comment by nithyanandan** [comment]
Few commits following up to https://github.com/nithyanandan/MOFF/commit/ee36176ec10975003d15d3b9718c631be86acb7c have added and tested this feature. Closing this issue until any inconsistent behavior noted.
