### ISSUE TITLE
Phases of simulated E-fields

### ISSUE THREAD

**Issue by adampbeardsley** [nithyanandan/MOFF#5]
In the sim_observe module, when creating a stochastic E timeseries, the position of the source is shifted by a "ref_point", which seems to be handled incorrectly. 
More detail...
 Line 276 of sim_observe.py:
`skypos_dot_antpos = NP.dot(skypos-ref_point, antpos.T)`
In the case of skypos=(0,0,1) and the default ref_point=(0,0,1), this removes any phases that should arise from varying heights of antennas. I suspect this is also not correct for off-center sources.
Suggested solution:
I think the shifted position should still be a unit vector. So perhaps (l,m) should be differenced, then n calculated. Something like this:
`diffpos = skypos-ref_point`
`diffpos[3] = NP.sqrt(1-NP.sum(diffpos[0:2]**2))`
`skypos_dot_antpos = NP.dot(diffpos, antpos.T)`

**Comment by adampbeardsley** [comment]
After offline discussion I'm convinced I was misinterpreting this reference point and that it is indeed correct.
As written, we are assuming that each antenna is independently phased to the reference. So in the case that a source is at the reference location, indeed the heights of antennas should not come in. However, off-reference sources will depend on the heights. 
One can think about this as setting a single phase offset for each antenna where
`phi_a = x_a * l_a + y_0 * m_0 + z_a * n_0`
This is perfectly valid, and I no longer have a problem with it.
I'll wait for Nithya to confirm before I close the issue though.

**Comment by nithyanandan** [comment]
Is this still considered a bug? Downgrading it to a "question" and closing it until further discussion.

**Comment by adampbeardsley** [comment]
I think this has been fully resolved. It was correct in code all along.
